brand: "Meddle"
url: "https://meddle.studio"
title: "Meddle"
description: "Meddle is a brand and design studio for industry challengers who aren't afraid to interfere with the status quo."
logo: "/assets/images/logo.svg"
logoWht: "/assets/images/logo-wht.svg"
logoMark: "/assets/images/apple-touch-icon.png"
image: "/assets/images/meddle-thumb.png"
addressLine1: "7901 4th St N, STE 300"
addressLine2: "St. Petersburg, FL, 33702"
supportEmail: "hello@meddle.studio"
#supportPhone: "877-626-9378"
gtm: "GTM-5S4496S9"
#facebook: "https://www.facebook.com/HUSTLFinancial"
#twitter: "http://x.com/hustlfinancial"
#linkedin: "https://www.linkedin.com/company/hustlfinancial"
instagram: "https://www.instagram.com/meddledesign.co/"

# Build settings
markdown: kramdown
#plugins:
  #- jekyll-redirect-from
exclude:
#  - .forestryio
# - _css
#  - _js
#  - _site/feed.xml
  - node_modules
  - CHANGELOG.md
  - Gemfile*
  - gulpfile.js
  - README.md
  - firebase.json
#  - README-forestry.md
#  - yarn.lock
  - vendor
#future: false
#collections:
#  pages:
#    output: false
#  menus:
#    output: false
defaults:
  -
    scope:
      path: ""
    values:
      layout: default



